Repository ahmedabougabal/ITICafeFoodDeliveryApp, pull requests merged in 2024-10, with the labels that each got.

#36 feat: Update client-side auth and user components
  .idea/material_theme_project_new.xml
  client/package-lock.json
  client/src/App.tsx
  client/src/UserContext.tsx
  client/src/components/AuthMessage.tsx
  client/src/components/Header/Header.tsx
  client/src/components/user/EditProfile.tsx
  client/src/components/user/Login.tsx
  client/src/components/user/Profile.tsx
  client/src/services/AuthService.ts
  client/src/services/FoodService.tsx
  client/src/utils/AxiosInstance.jsx
  client/src/utils/AxiosInstance.tsx
Labels: bug, enhancement, help wanted

#40 fix errors
  backend/iti_cafe/settings.py
  backend/users/serializers.py
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.module.css
  client/src/components/user/EditProfile.css
  client/src/components/user/EditProfile.jsx
  client/src/components/user/Login.jsx
  client/src/components/user/PasswordResetRequest.jsx
  client/src/components/user/Profile.jsx
  client/src/components/user/ResetPassword.jsx
  client/src/components/user/Signup.jsx
  client/src/components/user/VerifyEmail.jsx
  client/src/components/user/login.css
  client/src/components/user/passwordRequest.css
  client/src/components/user/profile.css
  client/src/components/user/signup.css
  client/src/components/user/verify.css
  client/src/index.css
  client/src/main.tsx
  client/src/services/AuthService.ts
Labels: bug

#50 Feat(home UI): Adds Significant Improvements to the UI of the homepag…
  client/src/pages/Home/HomePage.module.css
  client/src/pages/Home/HomePage.tsx
  client/src/pages/Home/iti_wallpaper.jpg
Labels: enhancement, New Feature, UI Improvement

#53 Add fixture data for ITI branches to be loaded instantly into the dat…
  backend/core/fixtures/initial_branches.json
Labels: enhancement

#54 FIX&Feat: Implementing the right data format to be sent from the fro…
  backend/core/migrations/0001_initial.py
  backend/debug.log
  backend/iti_cafe/settings.py
  backend/menu/migrations/0001_initial.py
  backend/orders/migrations/0001_initial.py
  backend/orders/migrations/0002_initial.py
  backend/orders/permissions.py
  backend/orders/serializers.py
  backend/orders/views.py
  backend/rooms/migrations/0001_initial.py
  backend/users/admin.py
  backend/users/migrations/0001_initial.py
  backend/users/models.py
Labels: enhancement, New Feature

#55 Feat_Fix: UI_OrderSuccess_functionality & 400 and 500s errors fix
  backend/media/menu_items/coffe.jpg
  backend/media/menu_items/food-1_RhWtXI4_a7vF7XH.jpg
  backend/media/menu_items/food-4_PWDcTeD.jpg
  backend/media/menu_items/licensed-image.jpeg
  backend/media/menu_items/licensed-image_p29TbA2_IAXlOmz.jpeg
  backend/media/menu_items/protein.webp
  backend/media/menu_items/protein_oxdYVow.webp
  backend/menu_items/coffe.jpg
  backend/menu_items/protein.webp
  client/src/AppRoutes.tsx
  client/src/hooks/useCart.tsx
  client/src/pages/Cart/CartPage.tsx
  client/src/pages/OrderSuccessPage.tsx
  client/src/pages/orderSuccessPage.module.css
  client/src/services/orderService.ts
Labels: enhancement, New Feature, UI Improvement

#52 registrtion design added
  Pipfile
  backend/core/migrations/0001_initial.py
  backend/debug.log
  backend/media/menu_items/food-1_xi8H0cU.jpg
  backend/media/menu_items/food-3.jpg
  backend/menu/migrations/0001_initial.py
  backend/menu/views.py
  backend/orders/migrations/0001_initial.py
  backend/rooms/migrations/0001_initial.py
  backend/users/migrations/0001_initial.py
  client/package-lock.json
  client/package.json
  client/public/images/bg-registration-form-1.jpg
  client/public/images/d
  client/public/images/ded
  client/public/images/pG.png
  client/public/images/pg.jpg
  client/public/images/registration-form-1.jpg
  client/public/images/registration-form.jpg
  client/src/App.tsx
  client/src/AppRoutes.tsx
  client/src/components/Footer/Footer.jsx
  client/src/components/user/Login.jsx
  client/src/components/user/Signup.jsx
  client/src/components/user/signup/css/style.css
  client/src/components/user/signup/css/style.css.map
  client/src/components/user/signup/css/style.scss
  client/src/components/user/signup/fonts/material-design-iconic-font/css/material-design-iconic-font.css
  client/src/components/user/signup/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css
  client/src/components/user/signup/fonts/material-design-iconic-font/fonts/Material-Design-Iconic-Font.eot
  client/src/components/user/signup/fonts/material-design-iconic-font/fonts/Material-Design-Iconic-Font.svg
  client/src/components/user/signup/fonts/material-design-iconic-font/fonts/Material-Design-Iconic-Font.ttf
  client/src/components/user/signup/fonts/material-design-iconic-font/fonts/Material-Design-Iconic-Font.woff
  client/src/components/user/signup/fonts/material-design-iconic-font/fonts/Material-Design-Iconic-Font.woff2
  client/src/components/user/signup/fonts/poppins/Poppins-Regular.ttf
  client/src/components/user/signup/fonts/poppins/Poppins-SemiBold.ttf
  client/src/components/user/user.css
  client/src/main.tsx
Labels: UI Improvement

#59 feat_FIX: Implements Django admin-authentication app for handling a whole…
  backend/debug.log
  backend/iti_cafe/settings.py
  backend/iti_cafe/urls.py
  backend/orders/urls.py
  backend/orders/views.py
  backend/users/admin.py
  backend/users/models.py
  struct.txt
Labels: enhancement, New Feature

#60 Enhance: Implements a breath-taking UI for the admin panel frontend +…
  admin-panel/src/components/DetailsModal/DetailsModal.js
  admin-panel/src/components/OrderComponent/OrderComponent.js
  admin-panel/src/components/OrderComponent/OrderItem.js
  admin-panel/src/components/OrderComponent/OrderList.js
  admin-panel/src/components/OrderComponent/PendingOrdersList.js
  admin-panel/src/components/header/AppHeaderDropdown.js
  admin-panel/src/routes.js
  admin-panel/src/views/orders/Orders.js
Labels: enhancement, New Feature, UI Improvement

#61 Implement services and state management for admin panel
  admin-panel/src/services/api.js
  admin-panel/src/services/orderService.js
  admin-panel/src/slices/orderSlice.js
Labels: enhancement, New Feature, UI Improvement

#62 feat: Add admin_auth app and utility functions
  backend/admin_auth/__init__.py
  backend/admin_auth/admin.py
  backend/admin_auth/apps.py
  backend/admin_auth/migrations/__init__.py
  backend/admin_auth/models.py
  backend/admin_auth/tests.py
  backend/admin_auth/urls.py
  backend/admin_auth/views.py
  backend/utils/__init__.py
  backend/utils/email_utils.py
Labels: enhancement

#63 feat: adds assets and packages for glass-morphism UI , a private rout…
  admin-panel/package.json
  admin-panel/src/App.js
  admin-panel/src/assets/images/1.png
  admin-panel/src/assets/images/3.jpeg
  admin-panel/src/assets/images/4.jpeg
  admin-panel/src/assets/images/edit.jpg
  admin-panel/src/assets/images/grad.jpeg
  admin-panel/src/components/admin/AdminLogin.css
  admin-panel/src/components/admin/AdminLogin.js
  admin-panel/src/components/admin/AdminLogout.js
  admin-panel/src/components/admin/PendingOrders.js
  admin-panel/src/components/admin/PrivateRoute.js
  admin-panel/src/utils/withAuth.js
Labels: documentation, enhancement, New Feature, UI Improvement

#64 Fix: adds missing active orders endpoint to be utilize the retrieval …
  backend/debug.log
  backend/orders/urls.py
Labels: bug, enhancement

#65 deletion: deletes tree which was used in debugging
  struct.txt
Labels: documentation

#67 created endpoint to notify users by email
  backend/debug.log
  backend/orders/urls.py
  backend/orders/views.py
  backend/users/views.py
Labels: New Feature

#69 Update .gitignore to ignore debug.log and conflicting files
  backend/.gitignore
  backend/debug.log
Labels: enhancement

#71 Fix&Refactor OrderCard component: Add preparation time validation and sim…
  admin-panel/src/components/OrderComponent/OrderCard.js
Labels: bug, enhancement, New Feature, UI Improvement

#73 Refactor order management components and update backend settings
  admin-panel/src/components/admin/PendingOrders.js
  admin-panel/src/views/orders/Orders.js
  backend/iti_cafe/settings.py
Labels: New Feature

#75 updated active orders
  backend/orders/views.py
Labels: enhancement

#80 Add new API endpoint for sales statistics
  backend/orders/urls.py
Labels: enhancement, New Feature

#81 Add dashboard component to display sales statistics
  admin-panel/src/views/dashboard/Dashboard.js
Labels: enhancement, New Feature, UI Improvement

#88 Feat: Improved Charts X&Y axes while enhancing Visuals & Animations
  admin-panel/package.json
  admin-panel/src/assets/images/avatars/8.jpg
  admin-panel/src/views/dashboard/Dashboard.js
  backend/orders/views.py
Labels: enhancement, New Feature, UI Improvement

#89 Fix: Adds Missing assets to fix the issue resulted from 'cannot resol…
  admin-panel/src/assets/images/avatars/1.jpg
  admin-panel/src/assets/images/avatars/2.jpg
  admin-panel/src/assets/images/avatars/23.jpg
  admin-panel/src/assets/images/avatars/3.jpg
  admin-panel/src/assets/images/avatars/4.jpg
  admin-panel/src/assets/images/avatars/5.jpg
  admin-panel/src/assets/images/avatars/6.jpg
  admin-panel/src/assets/images/avatars/7.jpg
  admin-panel/src/assets/images/avatars/9.jpg
  admin-panel/src/components/OrderComponent/CompletedOrderCard.js
  admin-panel/src/components/OrderComponent/PendingOrderCard.js
  admin-panel/src/components/OrderComponent/PreparingOrderCard.js
Labels: enhancement

#90 Feat/Enhance: Dashboard now displays a complete Statistical sales sta…
  admin-panel/src/views/dashboard/Dashboard.js
Labels: enhancement, New Feature, UI Improvement

#91 Feat: Added an hour view if sales-stats is displayed by today & adjus…
  backend/orders/views.py
Labels: New Feature, UI Improvement

#98 Feat_Enhance : Comprehensive UI/UX update: Modernize components and e…
  backend/debug.log
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.module.css
  client/src/components/Thumbnails/Thumbnails.tsx
  client/src/pages/Cart/CartPage.tsx
  client/src/pages/Cart/cartpage.module.css
  client/src/pages/Home/HomePage.tsx
  client/src/pages/Order/ActiveOrder.tsx
  client/src/pages/Order/ActiveOrders.module.css
  client/src/pages/orderSuccessPage.module.css
Labels: enhancement, New Feature, UI Improvement

#100 Feat_Fix : fixed price tag bug where on checkout, total price is NaN,…
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Thumbnails/Thumbnails.tsx
  client/src/hooks/useCart.tsx
Labels: bug, enhancement, New Feature

#102 Backend: Enhance menu functionality and add favorites API
  backend/menu/urls.py
  backend/menu/views.py
  backend/menu_items.json
  backend/menu_items/burger.jpg
  backend/menu_items/chickenSupreme.jpg
  backend/menu_items/omelete.jpg
Labels: documentation, enhancement, New Feature, UI Improvement

#103 Frontend: Implement favorites feature and improve UI/UX
  client/src/App.tsx
  client/src/FavoritesContext.tsx
  client/src/api/axiosConfig.ts
  client/src/components/FavoritesPage.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.module.css
  client/src/components/Thumbnails/Thumbnails.tsx
  client/src/components/ui/Card.tsx
  client/src/services/FoodService.tsx
Labels: enhancement, New Feature, UI Improvement

#104 Adds Missing Translation assets for the admin panel UI
  admin-panel/public/i18n/ar.json
  admin-panel/public/i18n/en.json
  admin-panel/src/i18n.js
Labels: bug

#108 feat(Header): Add hover functionality for chat notifications, Mobile Navigation Support (reshaped navbar for smaller displays), Fixed UI of received notifications , adds on mouse enter and on mouse leave functionalities
  client/src/components/Header/Header.tsx
Labels: enhancement, New Feature, UI Improvement

#110 feats_fixes: Reshaped the logic and UI of the header, Complete resolv…
  backend/core/migrations/0001_initial.py
  backend/menu/migrations/0001_initial.py
  backend/orders/migrations/0001_initial.py
  backend/orders/migrations/0002_initial.py
  backend/orders/migrations/0003_remove_notification_is_read.py
  backend/rooms/migrations/0001_initial.py
  backend/rooms/migrations/0002_initial.py
  backend/users/migrations/0001_initial.py
  client/src/components/Header/Header.tsx
Labels: enhancement, New Feature, UI Improvement

#112 Comprehensive Features Explanation from a quite close perspective dev…
  README.md
Labels: documentation

#123 feat(cart): Renhanced the whole project' visuals & Add new cart compo…
  client/public/cleanDuck.gif
  client/src/pages/Cart/EmptyCart.tsx
  client/src/pages/Cart/QuantityControl.tsx
Labels: enhancement, New Feature, UI Improvement

#124 Feat: Updated requirements.txt for developers willing to easily setup…
  backend/media/menu_items/burger_H30Sbue.jpg
  backend/media/menu_items/chickenSupreme_IasLKga.jpg
  backend/media/menu_items/coffe_GAI5gzo.jpg
  backend/media/menu_items/protein_GLGvQnL.webp
  backend/requirements.txt
Labels: enhancement

#126 Enhances Readability and Updated the Quote
  README.md
Labels: documentation
