Repository ahmedabougabal/ITICafeFoodDeliveryApp, pull requests merged in 2024-09, with the labels that each got.

#8 feat: Introduces menu views and urls for handling business logic and …
  backend/menu/urls.py
  backend/menu/views.py
Labels: documentation, enhancement

#9 feat: Implements both orders' serializers and models
  backend/orders/models.py
  backend/orders/serializers.py
Labels: documentation, enhancement

#10 feat: Implement OrderViewSet and configure URLs for orders app
  backend/orders/urls.py
  backend/orders/views.py
Labels: documentation, enhancement

#12 fix and feat: fixed wrong imported name in users/apps.py and ran migr…
  backend/.gitignore
  backend/iti_cafe/__pycache__/settings.cpython-312.pyc
  backend/iti_cafe/__pycache__/urls.cpython-312.pyc
  backend/menu/__pycache__/models.cpython-312.pyc
  backend/orders/__pycache__/models.cpython-312.pyc
  backend/users/__pycache__/admin.cpython-312.pyc
  backend/users/__pycache__/apps.cpython-312.pyc
  backend/users/__pycache__/models.cpython-312.pyc
  backend/users/apps.py
  backend/users/migrations/0001_initial.py
  backend/users/migrations/__init__.py
Labels: bug, documentation, enhancement

#15 feat_fix: feat: Update User model to handle last_login field correctl…
  backend/users/models.py
Labels: documentation, enhancement

#22 Resolving Git Headache (conflicts)
  backend/orders/models.py
  backend/orders/serializers.py
  backend/users/models.py
Labels: bug, enhancement

#33 auth components added
  backend/iti_cafe/settings.py
  backend/menu/admin.py
  backend/menu_items/food-1.jpg
  backend/menu_items/food-4.jpg
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/AppRoutes.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Login.tsx
  client/src/components/Register.tsx
  client/src/components/user/EditProfile.tsx
  client/src/components/user/Login.tsx
  client/src/components/user/PasswordResetRequest.tsx
  client/src/components/user/Profile.tsx
  client/src/components/user/ResetPassword.tsx
  client/src/components/user/Signup.tsx
  client/src/main.tsx
Labels: enhancement, help wanted
